jd_scripts:
  image: lxk0301/jd_scripts
  # 配置服务器资源约束。此例子中服务被限制为使用内存不超过200M以及cpu不超过0.2（单核的20%）
  # 经过实际测试，建议不低于200M
  # deploy:
  #   resources:
  #     limits:
  #       cpus: '0.2'
  #       memory: 200M
  container_name: jd_scripts
  restart: always
  volumes:
    - ./logs:/scripts/logs
  tty: true
  # 因为更换仓库地址可能git pull的dns解析不到，可以在配置追加hosts
  extra_hosts:
    - "gitee.com:180.97.125.228"
    - "github.com:13.229.188.59"
    - "raw.githubusercontent.com:151.101.228.133"
  environment:
    #脚本更新仓库地址，配置了会切换到对应的地址
    - REPO_URL=git@gitee.com:lxk0301/jd_scripts.git
    # 注意环境变量填写值的时候一律不需要引号（""或者''）下面这些只是示例，根据自己的需求增加删除
    #jd cookies
    # 例: JD_COOKIE=pt_key=XXX;pt_pin=XXX;
    # 例（多账号）: JD_COOKIE=pt_key=XXX;pt_pin=XXX;&pt_key=XXX;pt_pin=XXX;&pt_key=XXX;pt_pin=XXX;
    - JD_COOKIE=pt_key=AAJgygM0ADBKetTM2t7xGWap9ovZ1OO_fiNDUPxVOvaHb_Di3BhE_RZsbL2QRKRKvdM9z2ii80Y;pt_pin=1396539283_m;&pt_key=AAJglOKtADAin6dtHB0HZ2LR4crDppUVmXBNCxyxfeKCsPTFVf0xne7w7wJi0NtrTcu8VfNtr6A;pt_pin=jd_4c548c28526c4;&pt_key=AAJglOH9ADCLlszv1MrCSCyH9JSWTPtrkUS5eq2aetXwuKbCtG6IgZWGwOCYnZoje0XhRegSxzQ;pt_pin=jd_eOfPCENDTtLJ;&pt_key=AAJgygkXADAhNv6Bnv6KArhWkCWBdKSvMz8b7SjQc6ot5nlCoQqjU2vUVU2_1Gv3Gek1Jj3EuBw;pt_pin=jd_rTMWTlfeqnsH;&pt_key=AAJgqJHzADDCV-2cqAuoBSjCDHU3t54v_UrHDPYBUfdgvFLa7b8POMIDyjK0cbIVCNf7lEizOdY;pt_pin=jd_uksNrZhNVCND;&pt_key=AAJgrHvqADBySGc0YHazJE2OSfvUADMbGlyzHkcQuw1q_zOWqmyUhsCZIQR7J5H6PzUMh_KfBm4;pt_pin=jd_7f507f48d5222;&pt_key=AAJgsdjrADBRfggNIalFy9nyfJeGENQwUho53Cb312QzFgTxU6cPoqJVl0eEg7tnKHorNaVb7pQ;pt_pin=jd_681fde9bc2bb6;&pt_key=AAJgsdQ6ADC_gp-GuBi9wiwz5lsqt9jm64iCkDt5EMD86yscvfIJqvr6AisRFTLn6xXc_Frnlaw;pt_pin=xk0829;&pt_key=AAJgtCfJADAbBvCAJR9G0DXop1Fx2L80Tuby76xMYbA_W3-RsAiIItwCtliriv99mkwFQhTGWJc;pt_pin=ljbljb007;&pt_key=AAJgr1-zADA5-lRM9Rb3Nnemym29MRCO6XlpslqsSA-J4gGMul9vYlbbb10l7ji_X2MOOLgmp4U;pt_pin=30899948-352518;&pt_key=AAJgtlJoADDPRUTxeZSrifnqq_hAo9IH33v_7buoysS1MTJGLjfBruhEmWeuIG2wk7iLgRfrgWY;pt_pin=jd_75701f2b1dbc5;&pt_key=AAJgr2ArADBcOdESRintPlywinIph0l1BFRkUPGryNwKWDxFPTrXm_igWT46gI5KJ-pTU9_plKQ;pt_pin=jd_7cc4caf856eea;&pt_key=AAJgxYWxADCf3fBLnIvUl8pv0JiFWTrtwU598lHHQqBZ9EMdaf6-wc0T-L_mD0QjuW9qIkJxCy;pt_pin=SAK33;
    #微信server酱通知
    - PUSH_KEY=SCT27732T4mhGM4BTMgwtc6G5BvM4dBRX
    #Bark App通知
    - BARK_PUSH=
    #telegram机器人通知
    - TG_BOT_TOKEN=
    - TG_USER_ID=
    #钉钉机器人通知
    - DD_BOT_TOKEN=
    - DD_BOT_SECRET=
    #企业微信机器人通知
    - QYWX_KEY=
    #京东种豆得豆
    - PLANT_BEAN_SHARECODES=
    #京东农场
    # 例: FRUITSHARECODES=京东农场的互助码
    - FRUITSHARECODES=
    #京东萌宠
    # 例: PETSHARECODES=东东萌宠的互助码
    - PETSHARECODES=
    # 宠汪汪的喂食数量
    - JOY_FEED_COUNT=
    #东东超市
    # - SUPERMARKET_SHARECODES=
    #兑换多少数量的京豆（20，或者1000京豆,或者其他奖品的文字）
    # 例: MARKET_COIN_TO_BEANS=1000
    - MARKET_COIN_TO_BEANS=

    #如果设置了 RANDOM_DELAY_MAX ，则会启用随机延迟功能，延迟随机 0 到 RANDOM_DELAY_MAX-1 秒。如果不设置此项，则不使用延迟。
    #并不是所有的脚本都会被启用延迟，因为有一些脚本需要整点触发。延迟的目的有两个，1是降低抢占cpu资源几率，2是降低检查风险（主要是1）
    #填写数字，单位为秒，比如写为 RANDOM_DELAY_MAX=30  就是随机产生0到29之间的一个秒数，执行延迟的意思。
    - RANDOM_DELAY_MAX=120
